CREATE TABLE categoria (
  id BIGINT AUTO_INCREMENT NOT NULL,
   titulo VARCHAR(255) NOT NULL,
   cor VARCHAR(255) NOT NULL,
   CONSTRAINT pk_categoria PRIMARY KEY (id)
);

CREATE TABLE video (
  id BIGINT AUTO_INCREMENT NOT NULL,
   titulo VARCHAR(255) NOT NULL,
   descricao VARCHAR(255) NOT NULL,
   url VARCHAR(255) NOT NULL,
   categoria_id BIGINT,
   CONSTRAINT pk_video PRIMARY KEY (id)
);

ALTER TABLE video ADD CONSTRAINT FK_VIDEO_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES categoria (id);